name: ChopTree2
main: me.Iso.ChopTree.ChopTree
version: 2.2.2
author: ellbristow
softdepend: [Res, Towny, MyChunk, WorldGuard]
commands:
  choptree:
    description: Main plugin controls
    aliases:
      ct
  togglechop:
    description: Toggle ChopTree
    permission: choptree.commands.togglechop
    aliases:
      tc
permissions:
  choptree.*:
    description: Can chop and use all commands
    children:
      choptree.chop: true
      choptree.commands.*: true
  choptree.chop:
    description: Player can chop trees in one chop
  choptree.commands.*:
    description: Access to all commands
    children:
      choptree.commands.choptree.*: true
      choptree.commands.togglechop: true
  choptree.commands.choptree.*:
    description: Access to all admin commands
    children:
      choptree.commands.choptree.reload: true
      choptree.commands.choptree.info: true
      choptree.commands.choptree.toggle.*: true
  choptree.commands.choptree.info:
    description: Access to /choptree
  choptree.commands.choptree.reload:
    description: Access to /choptree reload
  choptree.commands.choptree.toggle.*:
    description: Can toggle all choptree settings
    children:
      choptree.commands.choptree.toggle.activebydefault: true
      choptree.commands.choptree.toggle.useanything: true
      choptree.commands.choptree.toggle.moredamagetotools: true
      choptree.commands.choptree.toggle.interruptiftoolbreaks: true
      choptree.commands.choptree.toggle.logsmovedown: true
      choptree.commands.choptree.toggle.onlytrees: true
      choptree.commands.choptree.toggle.leaves: true
  choptree.commands.choptree.toggle.activebydefault:
    description: Can toggle this setting
  choptree.commands.choptree.toggle.useanything:
    description: Can toggle this setting
  choptree.commands.choptree.toggle.moredamagetotools:
    description: Can toggle this setting
  choptree.commands.choptree.toggle.interruptiftoolbreaks:
    description: Can toggle this setting
  choptree.commands.choptree.toggle.logsmovedown:
    description: Can toggle this setting
  choptree.commands.choptree.toggle.onlytrees:
    description: Can toggle this setting
  choptree.commands.choptree.toggle.leaves:
    description: Can toggle this setting
  choptree.commands.togglechop:
    description: Access to /togglechop
